### ISSUE TITLE
[Bug] App Monitorizare Vot -> Incarcare imagine/video device cu Android

### ISSUE THREAD

**Issue by imoreanu** [code4romania/mon-vot-android-kotlin#171] opened 2019-11-23 10:55 UTC
**Environment:**
Mobil Huawei  P9 Lite-> OS Android 7.0
**Steps to Reproduce:**
1. Accesare aplicatie;
2. Alegere oras & Sectie;
3. Alegere optiunea Deschidere (duminica)/ oricare din optiunile care au impementata functia de adaugare/incarcare content;

**Expected Results:**
3. La tap pe optiunea "incarca imagine" || incarca video ar trebui sa se deschida camera si dupa fotgrafiere sau filmare, sa pot incarca contentul in aplicatie;

**Actual results:**
La tap pentru optiunile "fotgrafiaza" || inregistreaza video sunt dat afara din app;
![Screenshot from 2019-11-23 12-53-44](https://user-images.githubusercontent.com/47196725/69477580-8dc48480-0df0-11ea-8d2e-6d407dfce3f6.png)

**Comment by ssand** [comment] 2020-10-27 10:54
@Angeliqus
I've tested the master branch code (v2.0.7-b35) on 4 devices:
- Nexus 5, Android 6.0.1
- Huawei P9 Lite, Android 7.0
- Samsung Galaxy Note 3, Android 5.1.1
- Pixel 2, Android 11
Couldn't reproduce the issue on any of the devices.
Can you confirm please that the issue is still present?

**Comment by aniri** [comment] 2020-11-08 10:55
closing this as it cannot be reproduced

**Closed as completed by aniri** 2020-11-08 10:55 UTC
Labels: bug, autumn-2020, code4ro-hackdays
