### ISSUE TITLE
[BUG] The answer to a question is missed if pressing the back button

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#249] opened 2020-11-28 09:52 UTC
Steps to reproduce:

> Go to forms screen -> select one form -> select a question -> choose an answer -> hit BACK(the system button) -> app makes an empty POST request to /answers(which is successful)-> the app shows the question with green(as answered). 
> The answers are not saved in the backend

The selected answer should either be correctly sent to the server with the POST request or removed from answered questions. We should not miss answers :/

**Comment by AndreiToader-tomtom** [comment] 2020-11-28 16:11
I will take a look.

**Comment by toaderandrei** [comment] 2020-11-28 16:12
I will take a look.

**Comment by lukstbit** [comment] 2020-11-28 17:46
@aniri @toaderandrei 

I think I understand why this happens. When the user goes BACK in `QuestionsDetailsFragment.onPause` we save the current answer and also try to sync the answers provided by the user. At this point there's a race condition between saving this last item and syncing the answers. Sometimes the answer is saved in the database before syncing and everything is ok and other times the sync(more precisely the database call getting the unsynced answers) happens before the last answer is saved to the database and the repository syncs an empty list of answers.

In the `Repository.syncAnswers()` method the problem is that the we update the answer in the database even if the post call was done with an empty list of answers(race condition above). So the answer wasn't actually synced but marked as synced in the database in the end(and silently losing the answer).

**Comment by toaderandrei** [comment] 2020-11-28 17:48
well, I already fixed it. I am testing it.

**Comment by aniri** [comment] 2020-11-29 09:21
@lukstbit @toaderandrei thanks a lot for your help with this! I've reopened the PR by lukstbit and will test both thoroughly later today. As we're so close to the election date we need the cleanest and easier fix now, and we'll probably have to include this later in a more bigger refactoring. Probably combined with the error handling part that @toaderandrei started :smiley:

**Closed as completed** 2020-11-30 15:45 UTC
Labels: bug, help wanted, kotlin, high-priority, autumn-2020, code4ro-hackdays
